### PR TITLE
Fix for #154 and #160

### LINKED ISSUE #154: Google Home Mini in different subnet does not work any more
### Contact Details

_No response_

### What happened?

I used version 2.3.1 for quite some time successfully.
Now I updated to the newest version 3.1.0 and it does not work any more.

Situation:
- iobroker is installed on a Raspberry Pi in subnet 3 (192.168.3.XXX)
- 3 Google Home Minis are separated in subnet 66 (192.168.66.YYY)

Error message is that the adapter cannot get MAC addresses for the devices (see log below).
I assume, the problem there is the breaking change in 3.0.3 from jey cee that object IDs are now mac addresses instead of names. As MAC addresses are only available for devices located in the same subnet in the ARP-table, there is no way for the adapter to figure out the MAC addresses of the devices.

As I entered the IP addresses in the configuration and (at least until version 2.3.1) this worked, I assume it is sufficient to contact the devices via their IP addresses. Why is the MAC address required/used for the object IDs? The "old" object IDs also have been very stable against hardware changes. Id one Google Home Mini was broken, another one could be configured and used and the object id names did not change, so no need to update e.g. scripts.

Can I use the newer versions of this adapter anyhow? Moving the Google Home Minis in the subnet 3 is not an option for me...

### Adapter Version

3.1.0

### JS-Controller Version

4.0.24

### Node JS Version

v16.18.1

### NPM Version

8.19.2

### Operating System

Ubuntu

### Relevant log output

```shell
chromecast.0
	2023-01-22 11:08:47.855	error	Google_Home_Wohnzimmer - Error: The id is empty! Please provide a valid id.
chromecast.0
	2023-01-22 11:08:47.807	error	Google_Home_Wohnzimmer - Cannot get MAC for "192.168.66.107": TypeError: Cannot read properties of undefined (reading 'replaceAll')
chromecast.0
	2023-01-22 11:08:47.805	error	Google_Home_Eingang - Error: The id is empty! Please provide a valid id.
chromecast.0
	2023-01-22 11:08:47.803	error	Google_Home_Kinderzimmer_Anna - Error: The id is empty! Please provide a valid id.
chromecast.0
	2023-01-22 11:08:47.796	error	Google_Home_Eingang - Cannot get MAC for "192.168.66.111": TypeError: Cannot read properties of undefined (reading 'replaceAll')
chromecast.0
	2023-01-22 11:08:47.788	error	Google_Home_Kinderzimmer_Anna - Cannot get MAC for "192.168.66.109": TypeError: Cannot read properties of undefined (reading 'replaceAll')
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by neopholus**
Trying to read id from configuration before trying to determine MAC as ID to fix #154 and #160.
Add additional documentation on the Device tab.

### CODE REVIEW

**Comment by neopholus** [comment]
I am new as active contributor here. If something is wrong or missing, please let me know so that I can fix it.

**Comment by mcm1957** [comment]
@neopholus 

Thanks for providing this PR. If noone else takes care I will look at it in more detail end of march. I cannot work anything for ioBroker starting next week and lasting app 2 weeks. If I forget and this PR is still open, please ping my by adding a comment and notice me @mcm1957 

From the technical view (and after a first look) I would suggest to use the mac address if available and to use the name only as fallback. This would avoid a breaking change for existing users and keep the idea of unique state names.

In any case the name provided by users must be filtered much more. It might not contain any of the forbidden characters. So at minimum a "replace(adapter.FORBIDDEN_CHARS, '_')" is reuired but '.', ' ' must be replaced in addition. (Spaces are known to cause problems with some vis but are not blocke due to historical reasons). In general I would disallow any characters except [a-zA-Z0-9_-]. Further more a check should be added to ensure that the id is unique as non unique states could cause sideeffects.

**Comment by raintonr** [comment]
Also, please update the readme change log and add instructions for your proposed change.

**Comment by neopholus** [comment]
@raintonr: 
> Also, please update the readme change log and add instructions for your proposed change.
Thanks for the hint. Done.

@mcm1957:
> From the technical view (and after a first look) I would suggest to use the mac address if available and to use the name only as fallback. This would avoid a breaking change for existing users and keep the idea of unique state names.

I think, the expected behavior is different. If I define a device manually, I expect that the name, that I provided is used. I already added some documentation to the devices tab (and now also to the readme), that if user wants names to correspond  to the names of the automatically found devices, that the user must use the MAC address as name. Also I hope it will not be a breaking change, as usually users only added the devices manually when they have not been detected automatically. 

Thanks for the other hints, I try to add code to check the validity of the name as soon as possible.

**Comment by mcm1957** [comment]
If the name is preferred over the MAC its definitly breaking. But we could decide to do it and incremnte major version number. So this should be OK too.

**Comment by neopholus** [comment]
filtering names now as @mcm1957 recommended

**Comment by neopholus** [comment]
Added a check for duplicate IDs as @mcm1957 requested.

**Comment by neopholus** [comment]
Ping @mcm1957, I hope I did all the requested changes and commited them already.
If anything is missing, just tell me, I am still an beginner here with ioBroker adapters. And GitHub...

**Comment by neopholus** [comment]
Hi @mcm1957, 
if you find some time, please approve this workflow.... 
If anything is missing, just tell me, I will try and fix it.
Thanks, Stefan

**Pull request merged**
